services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: observability
    ports:
      - "5432:5432"
    volumes:
      - ../postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"

  netem-client:
    build:
      context: ../netem/client
    image: local/netem-node:arm64
    container_name: netem-client
    command:
      - sh
      - -c
      - |
        ip route add 10.10.2.0/24 via 10.10.1.254
        sleep infinity
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      client-net:
        ipv4_address: 10.10.1.10

  netem-router:
    build:
      context: ../netem/client
    image: local/netem-node:arm64
    container_name: netem-router
    command: sleep infinity
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      net.ipv4.ip_forward: "1"
    networks:
      client-net:
        ipv4_address: 10.10.1.254
      server-net:
        ipv4_address: 10.10.2.254

  netem-server:
    build:
      context: ../netem/client
    image: local/netem-node:arm64
    container_name: netem-server
    command:
      - sh
      - -c
      - |
        ip route add 10.10.1.0/24 via 10.10.2.254
        python3 -m http.server 8080
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      server-net:
        ipv4_address: 10.10.2.10

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - ../telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - "9273:9273"
    depends_on:
      - prometheus

networks:
  client-net:
    name: netem-client-net
    ipam:
      config:
        - subnet: 10.10.1.0/24

  server-net:
    name: netem-server-net
    ipam:
      config:
        - subnet: 10.10.2.0/24