data_dir = "/var/lib/vector"


###############################################################################
# Sorgente 1: file di log del router
###############################################################################

[sources.router_logs]
type = "file"
include = ["/logs/router.log"]
read_from = "beginning"

[sources.router_logs.fingerprint]
strategy = "device_and_inode"


###############################################################################
# Sorgente 2: server Syslog TCP
###############################################################################

[sources.syslog]
type = "syslog"
address = "0.0.0.0:5140"
mode = "tcp"


###############################################################################
# Trasformazione dei log provenienti dal file
###############################################################################

[transforms.parse_router_logs]
type = "remap"
inputs = ["router_logs"]

source = '''
.message = string!(.message)
.service_name = "router-file"
.event_time = now()
'''


###############################################################################
# Trasformazione dei messaggi Syslog
###############################################################################

[transforms.parse_syslog]
type = "remap"
inputs = ["syslog"]

source = '''
.message = string!(.message)
.service_name = "router-syslog"
.event_time = now()
'''


###############################################################################
# Output console
###############################################################################

[sinks.console]
type = "console"
inputs = [
    "filter_snmp_warning",
    "parse_syslog"
]
encoding.codec = "json"


###############################################################################
# Output PostgreSQL
###############################################################################

[sinks.postgres]
type = "postgres"
inputs = [
    "filter_snmp_warning",
    "parse_syslog"
]
endpoint = "postgresql://admin:admin@postgres:5432/observability"
table = "raw.log_events"

[sinks.postgres.batch]
max_events = 100
timeout_secs = 1

[transforms.filter_snmp_warning]
type = "filter"
inputs = ["parse_router_logs"]

condition = '''
!contains(
  string!(.message),
  "systemstats_linux: unexpected header length"
)
'''